# Generated by Django 4.0.4 on 2022-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUserURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField(unique=True, verbose_name='original link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('short', models.CharField(max_length=5, unique=True, verbose_name='short link')),
            ],
            options={
                'verbose_name': 'URL of an registered user',
                'verbose_name_plural': 'URLs of an registered user',
            },
        ),
        migrations.CreateModel(
            name='UnknownUserURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField(unique=True, verbose_name='original link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('short', models.CharField(max_length=8, unique=True, verbose_name='short link')),
            ],
            options={
                'verbose_name': 'URL of an unregistered user',
                'verbose_name_plural': 'URLs of an unregistered user',
            },
        ),
    ]
