# Generated by Django 4.0.4 on 2022-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_alter_registereduserurl_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduserurl',
            name='short',
            field=models.CharField(max_length=5, verbose_name='short link'),
        ),
        migrations.AlterField(
            model_name='unknownuserurl',
            name='short',
            field=models.CharField(max_length=8, verbose_name='short link'),
        ),
    ]
