# Generated by Django 4.0.4 on 2022-05-18 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlapp', '0003_alter_registereduserurl_short_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(verbose_name='original link')),
                ('short', models.CharField(max_length=8, unique=True, verbose_name='short link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.DeleteModel(
            name='RegisteredUserURL',
        ),
        migrations.DeleteModel(
            name='UnknownUserURL',
        ),
    ]
